name: Release

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    name: Publish this packages to npm registry
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@main
      - name: Setup Node.js 14.x
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Create release PR or publish to npm
        uses: changesets/action@master
        with:
          version: pnpm version
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
